global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "backend_app"
    static_configs:
      - targets: ["backend:9000"]

  - job_name: "ses_service"
    static_configs:
      - targets: ["service-ses:8002"]

  - job_name: "s3_service"
    static_configs:
      - targets: ["service-s3:8000"]
